### ISSUE TITLE
Practica: Animacion de Objeto 3D

### ISSUE THREAD

**Issue by EDITH-R** [SistemasTecTlaxiaco/practica-de-objeto-3d-en-blender-con-animacion-equipo-edith#1]
[Practica de animacion.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-objeto-3d-en-blender-con-animacion-equipo-edith/files/8364613/Practica.de.animacion.pdf)

**Comment by JulioCesar69** [comment]
Calificación: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
